//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Test.rc
//
#define IDD_ABOUTBOX                    100
#define CG_IDR_POPUP_TEST_VIEW          102
#define CG_IDD_CONTROLPANEL             103
#define CG_ID_VIEW_CONTROLPANEL         104
#define CG_IDD_HISTORYPANEL             105
#define CG_ID_VIEW_HISTORYPANEL         106
#define CG_IDD_TEST                     107
#define CG_ID_VIEW_TEST                 108
#define IDR_MAINFRAME                   128
#define IDR_TESTTYPE                    129
#define IDC_EDIT1                       1000
#define IDC_BUTTON1                     1001
#define IDC_BUTTON2                     1002
#define IDC_BUTTON3                     1003
#define IDC_BUTTON4                     1004
#define IDC_BUTTON5                     1005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
