//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Test.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_TEST_FORM                   101
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_TESTTYPE                    129
#define IDC_GETSTATUS                   1000
#define ID_CHANNELS_C1FOREST            32771
#define ID_CHANNELS_C1GARDEN            32772
#define ID_CHANNELS_CASTLE1             32773
#define ID_CHANNELS_CEMETARY            32775
#define ID_CHANNELS_HOUSA               32776
#define ID_CHANNELS_HOUSB               32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
