/*
0010mall;
0020mall;
0030mall;
0040mall;
0010smin;
0020smin;
0030smin;
0040smin;
*/
#include "DlgPDA.h"

	DWORD dwDU = 1400;
//	CUC2View* pView = GetUC2View();
	CString strText;
	CActor* pActor[10];

/////// Scene 1
	LoadStage("0010mall");
	Wait(dwDU);		if (!IsDemo())	break;
	m_pStage->CreateActor(20, CPoint(0,0), TRUE, AS_STAND | DA_FL, TRUE);
	pActor[0] = m_pStage->GetThisActor();
	ASSERT(pActor[0]);

	Wait(dwDU);		if (!IsDemo())	break;
	pActor[0]->Act(CMD_HELLO);
	Wait(dwDU*2);		if (!IsDemo())	break;
	strText = "도우미: 차세대 전자상거래 프로토타입인 m@ll에 오신 것을 환영합니다.";
	pActor[0]->Chat(strText);
	PlayWaveFile("01dou01.wav");
	DisplayText(strText);
	Wait(dwDU*3);		if (!IsDemo())	break;
	SendMoveCommand(CMD_MOVEF);
	Wait(dwDU);		if (!IsDemo())	break;
	strText = "도우미: M@ll 이란 온라인 쇼핑을 애니메이션과 삼차원 그래픽을 통해 누구나 쉽고 재미있게 접할 수 있는 가상공간의 쇼핑몰 입니다.";
	pActor[0]->Chat(strText);
	PlayWaveFile("01dou02.wav");
	DisplayText(strText);
	Wait(dwDU*6);		if (!IsDemo())	break;
	SendMoveCommand(CMD_MOVEF);
	Wait(dwDU);		if (!IsDemo())	break;
	SendMoveCommand(CMD_MOVEF);
	Wait(dwDU);		if (!IsDemo())	break;
	strText = "도우미: 사용자는 가상의 캐릭터를 선택하여 현실과 같은 가상공간에서 인터렉티브한 쇼핑을 즐길 수 있습니다.";
	pActor[0]->Chat(strText);
	PlayWaveFile("01dou03.wav");
	DisplayText(strText);
	Wait(dwDU*5);		if (!IsDemo())	break;
	strText = "도우미: 자 그럼 저의 안내를 따라 몰의 데모를 보시겠습니다.";
	pActor[0]->Chat(strText);
	PlayWaveFile("01dou04.wav");
	DisplayText(strText);
	Wait(dwDU*5);		if (!IsDemo())	break;
	SendMoveCommand(CMD_MOVEF);
	Wait(dwDU);		if (!IsDemo())	break;
	SendMoveCommand(CMD_MOVEF);
	Wait(dwDU);		if (!IsDemo())	break;
	SendMoveCommand(CMD_MOVEF);
	Wait(dwDU);		if (!IsDemo())	break;

/////// Scene 2
	strText = "도우미: 바로 이곳이 M@LL의 출발점 입니다.";
	pActor[0]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("02dou01.wav");
	Wait(dwDU*5);		if (!IsDemo())	break;
	strText = "도우미: 화면에 보시는 것과 같이 거리에 위치한 빌딩들은 각 회사의 전자 상거래 상점들 입니다.";
	pActor[0]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("02dou02.wav");
	Wait(dwDU*6);		if (!IsDemo())	break;
	pActor[1] = m_pStage->CreateActor(0, CPoint(92,262), FALSE, AS_STAND | DA_FL);
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[2] = m_pStage->CreateActor(5, CPoint(456,291), FALSE, AS_STAND | DA_FL);
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[3] = m_pStage->CreateActor(7, CPoint(557,245), FALSE, AS_STAND | DA_FR);
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[0]->SetState(AS_STAND | DA_BR);
	Wait(dwDU);		if (!IsDemo())	break;
	strText = "도우미: 저기 보이는 화살표를 따라가면 다음 블록의 쇼핑 사이트로 이동합니다.";
	pActor[0]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("02dou03.wav");
	Wait(dwDU*6);		if (!IsDemo())	break;

/////// Scene 3
	LoadStage("0020mall");
	Wait(dwDU*2);		if (!IsDemo())	break;
	pActor[0] = m_pStage->CreateActor(20, CPoint(0,0), TRUE, AS_STAND | DA_FL, TRUE);
	pActor[0] = m_pStage->GetThisActor();
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[0]->SetState(AS_STAND | DA_BR);
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[1] = m_pStage->CreateActor(0, CPoint(448,273), FALSE, AS_STAND | DA_FL);
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[2] = m_pStage->CreateActor(5, CPoint(490,321), FALSE, AS_STAND | DA_FL);
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[3] = m_pStage->CreateActor(7, CPoint(569,284), FALSE, AS_STAND | DA_FR);
	Wait(dwDU);		if (!IsDemo())	break;
	strText = "도우미: 보시는 것과 같이 여러 기업들의 상점들이 있습니다.";
	pActor[0]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("03dou01.wav");
	Wait(dwDU*6);		if (!IsDemo())	break;
	m_pStage->ActorMove(pActor[2], TRUE);	// Forward
	Wait(dwDU);		if (!IsDemo())	break;
	strText = "도우미: 현재 전자상거래를 지향하는 기업과 업체들은 이곳 몰의 가상공간에 입주 하실 수 있고 자동으로 온라인 광고를 하실 수가 있습니다.";
	pActor[0]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("03dou02.wav");
	Wait(dwDU*9);		if (!IsDemo())	break;
	strText = "도우미: 저기 보이는 멀티비젼에 실시간 온라인 광고를 하실 수 있습니다.  또한 광고의 이미지를 클릭하시면 각 회사의 웹사이트가 구동 됩니다.";
	pActor[0]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("03dou03.wav");
	Wait(dwDU*5);		if (!IsDemo())	break;
	CMainFrame* pMF = (CMainFrame*)AfxGetMainWnd();
	pMF->ShellBrowseURL("http://www.samsung.co.kr/");
	Wait(dwDU*8);		if (!IsDemo())	break;
	pMF->SetActiveWindow();

/////// Scene 4
	LoadStage("0030mall");
	Wait(dwDU*2);		if (!IsDemo())	break;
	pActor[0] = m_pStage->CreateActor(20, CPoint(0,0), TRUE, AS_STAND | DA_FL, TRUE);
	pActor[0] = m_pStage->GetThisActor();
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[0]->SetState(AS_STAND | DA_BR);
	Wait(dwDU);		if (!IsDemo())	break;
	strText = "도우미: 몰의 가상공간에서는 쇼핑만이 아닌 다른 사용자들과의 자유로운 대화를 나누며 정보를 교환 하실수도 있습니다.";
	pActor[0]->Chat(strText);
	PlayWaveFile("04dou01.wav");
	DisplayText(strText);
	Wait(dwDU*6);		if (!IsDemo())	break;
	pActor[1] = m_pStage->CreateActor(0, CPoint(276,177), FALSE, AS_STAND | DA_FL);
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[2] = m_pStage->CreateActor(5, CPoint(406,155), FALSE, AS_STAND | DA_FL);
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[3] = m_pStage->CreateActor(7, CPoint(459,293), FALSE, AS_STAND | DA_BL);
	Wait(dwDU);		if (!IsDemo())	break;
	strText = "거리1:  싸게 모뎀을 사려면 어디가 좋을까요?";
	pActor[1]->Chat(strText);
	DisplayText(strText);
	Wait(dwDU);		if (!IsDemo())	break;
	strText = "거리2:  저기 쇼핑 센터내에 위치한 401호 우주정보통신으로 가보세요";
	pActor[2]->Chat(strText);
	Wait(dwDU);		if (!IsDemo())	break;
	strText = "거리1:  감사합니다.";
	pActor[1]->Chat(strText);
	Wait(dwDU);		if (!IsDemo())	break;

/////// Scene 5
	LoadStage("0040mall");
	Wait(dwDU*2);		if (!IsDemo())	break;
	pActor[0] = m_pStage->CreateActor(20, CPoint(0,0), TRUE, AS_STAND | DA_FL, TRUE);
	pActor[0] = m_pStage->GetThisActor();
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[0]->SetState(AS_STAND | DA_BR);
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[1] = m_pStage->CreateActor(0, CPoint(365,289), FALSE, AS_STAND | DA_FL);
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[2] = m_pStage->CreateActor(5, CPoint(74,325), FALSE, AS_STAND | DA_FL);
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[3] = m_pStage->CreateActor(7, CPoint(580,230), FALSE, AS_STAND | DA_BL);
	Wait(dwDU);		if (!IsDemo())	break;

	pActor[1]->SetState(AS_STAND | DA_BL);
	Wait(dwDU);		if (!IsDemo())	break;
	strText = "갤러리1: 어 저거 삼성자동차 건물 아니에요?";
	pActor[1]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("05g1a01.wav");
	Wait(dwDU*4);		if (!IsDemo())	break;
	pActor[0]->SetState(AS_STAND | DA_BL);
	Wait(dwDU);		if (!IsDemo())	break;
	strText = "도우미: 예, 맞습니다.";
	pActor[0]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("05dou01.wav");
	Wait(dwDU*2);		if (!IsDemo())	break;
	strText = "그럼 삼성자동차 온라인 오토스테이션으로 가볼까요?.";
	pActor[0]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("05dou02.wav");
	Wait(dwDU*4);		if (!IsDemo())	break;
	strText = "네!";
	pActor[1]->Chat(strText);
	pActor[2]->Chat(strText);
	pActor[3]->Chat(strText);
	PlayWaveFile("05g1a02.wav");
	Wait(dwDU*2);		if (!IsDemo())	break;
	strText = "도우미: 그럼 저를 따라 오세요";
	pActor[0]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("05dou03.wav");
	Wait(dwDU*3);		if (!IsDemo())	break;
	SendMoveCommand(CMD_MOVEF);
	Wait(dwDU);		if (!IsDemo())	break;
	SendMoveCommand(CMD_MOVEF);
	Wait(dwDU);		if (!IsDemo())	break;
	SendMoveCommand(CMD_MOVEF);
	Wait(dwDU);		if (!IsDemo())	break;
	SendMoveCommand(CMD_MOVEF);
	Wait(dwDU);		if (!IsDemo())	break;
	SendMoveCommand(CMD_MOVEF);
	Wait(dwDU);		if (!IsDemo())	break;
	SendMoveCommand(CMD_MOVEF);
	Wait(dwDU);		if (!IsDemo())	break;
	SendMoveCommand(CMD_MOVEF);
	Wait(dwDU);		if (!IsDemo())	break;
	SendMoveCommand(CMD_MOVEF);
	Wait(dwDU);		if (!IsDemo())	break;

/////// Scene 6
	LoadStage("0010smin");
	Wait(dwDU*2);		if (!IsDemo())	break;
	pActor[0] = m_pStage->CreateActor(18, CPoint(0,0), TRUE, AS_STAND | DA_FL, TRUE);
	pActor[0] = m_pStage->GetThisActor();
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[0]->SetState(AS_STAND | DA_BR);
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[1] = m_pStage->CreateActor(0, CPoint(115,188), FALSE, AS_STAND | DA_FL);
	pActor[2] = m_pStage->CreateActor(5, CPoint(73,251), FALSE, AS_STAND | DA_FL);
	pActor[3] = m_pStage->CreateActor(7, CPoint(299,289), FALSE, AS_STAND | DA_BL);
	pActor[4] = m_pStage->CreateActor(2, CPoint(78, 319), FALSE, AS_STAND | DA_BL);
	Wait(dwDU);		if (!IsDemo())	break;
	SendMoveCommand(CMD_MOVEF);
	Wait(dwDU);		if (!IsDemo())	break;
	SendMoveCommand(CMD_MOVEF);
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[0]->SetState(AS_STAND | DA_FR);
	Wait(dwDU);		if (!IsDemo())	break;
	strText = "오도우미: 안녕하세요 오토스테이션에 오신 것을 환영합니다.";
	pActor[0]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("06odo01.wav");
	Wait(dwDU*4);		if (!IsDemo())	break;
	strText = "오도우미: 이곳은 구입부터 사후 A/S까지 종합적인 서비스를 제공하는 365일 온라인 오토스테이션입니다.";
	pActor[0]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("06odo02.wav");
	Wait(dwDU*6);		if (!IsDemo())	break;
	strText = "갤러리3: 그럼 여기서 바로 자동차를 구입할 수 있습니까?";
	pActor[3]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("06g3a01.wav");
	Wait(dwDU*4);		if (!IsDemo())	break;
	strText = "오도우미: 그렇습니다. 저기 보이는 김말동 딜러님을 소개해 드리겠습니다.";
	pActor[0]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("06odo03.wav");
	Wait(dwDU*5);		if (!IsDemo())	break;
	pActor[5] = m_pStage->CreateActor(19, CPoint(235,190), FALSE, AS_STAND | DA_FR);
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[0]->SetState(AS_STAND | DA_BR);
	Wait(dwDU);		if (!IsDemo())	break;
	strText = "김딜러: 안녕하십니까? 무엇을 도와드릴까요";
	pActor[5]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("06dea01.wav");
	Wait(dwDU*4);		if (!IsDemo())	break;
	strText = "갤러리3: SM525V의 사양과 가격에 대해서 알고 싶은데요.";
	pActor[3]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("06g3a02.wav");
	Wait(dwDU*4);		if (!IsDemo())	break;
	strText = "김딜러: 그럼 저기 돌아가는 SM525V를 클릭해 보십시오";
	pActor[5]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("06dea02.wav");
	Wait(dwDU*4);		if (!IsDemo())	break;
	CDlgPDA pda;
	pda.SetMode(TRUE, TRUE);
	pda.DoModal();
	strText = "김딜러: 그럼 견적과 할부제도에 대해 설명 드리겠습니다.";
	pActor[5]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("06dea03.wav");
	Wait(dwDU*5);		if (!IsDemo())	break;
	strText = "김딜러: 그럼 저를 따라오세요.";
	pActor[5]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("08dea03.wav");
	Wait(dwDU*3);		if (!IsDemo())	break;
	pActor[0]->SetState(AS_STAND | DA_BR);
	Wait(dwDU);		if (!IsDemo())	break;
	m_pStage->ActorMove(pActor[5], TRUE);	// Forward
	Wait(dwDU);		if (!IsDemo())	break;
	m_pStage->ActorMove(pActor[5], TRUE);	// Forward
	Wait(dwDU);		if (!IsDemo())	break;
	m_pStage->ActorMove(pActor[5], TRUE);	// Forward
	Wait(dwDU);		if (!IsDemo())	break;

/////// Scene 7
	LoadStage("0020smin");
	Wait(dwDU*2);		if (!IsDemo())	break;
	pActor[0] = m_pStage->CreateActor(18, CPoint(0,0), TRUE, AS_STAND | DA_FL, TRUE);
	pActor[0] = m_pStage->GetThisActor();
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[0]->SetState(AS_STAND | DA_BR);
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[5] = m_pStage->CreateActor(19, CPoint(290,170), FALSE, AS_STAND | DA_FL);
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[1] = m_pStage->CreateActor(0, CPoint(300,305), FALSE, AS_STAND | DA_BL);
	pActor[2] = m_pStage->CreateActor(5, CPoint(124,218), FALSE, AS_STAND | DA_FL);
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[3] = m_pStage->CreateActor(7, CPoint(67,270), FALSE, AS_STAND | DA_BL);
	pActor[4] = m_pStage->CreateActor(2, CPoint(95,170), FALSE, AS_STAND | DA_FL);
	Wait(dwDU);		if (!IsDemo())	break;
	strText = "김딜러: 저희 금융 메니저인 이메니저님을 소개해 드리겠습니다.";
	pActor[5]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("07dea01.wav");
	Wait(dwDU*6);		if (!IsDemo())	break;
	pActor[6] = m_pStage->CreateActor(19, CPoint(315,197), FALSE, AS_STAND | DA_FL);
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[6]->SetState(AS_STAND | DA_FR);
	Wait(dwDU);		if (!IsDemo())	break;
	m_pStage->ActorMove(pActor[6], TRUE);	// Forward
	Wait(dwDU);		if (!IsDemo())	break;
	strText = "이메니: 안녕하십니까? 무엇을 도와드릴까요?";
	pActor[6]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("07man01.wav");
	Wait(dwDU*5);		if (!IsDemo())	break;
	strText = "갤러리2: SM525V 견적가와 할부제도에 대해 알고 싶은데요.";
	pActor[2]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("07g2a01.wav");
	Wait(dwDU*5);		if (!IsDemo())	break;
	strText = "이메니: 견적서와 할부제도를 질문하신 분의 이메일 어카운트로 지금 즉시 송부해 드리겠습니다.";
	pActor[6]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("07man02.wav");
	Wait(dwDU*5);		if (!IsDemo())	break;
	CDlgPDA pda2;
	pda2.SetMode(TRUE, FALSE);
	pda2.SetPage(5, 4);
	pda2.DoModal();
	strText = "이메니: 추후 궁금하신 사항은 저기 보이는 엔젤 도우미가 자세한 설명을 해 드릴 겁니다.";
	pActor[6]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("07man03.wav");
	Wait(dwDU*5);		if (!IsDemo())	break;
	strText = "이메니: 다른 질문은 없습니까?";
	pActor[6]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("07man04.wav");
	Wait(dwDU*4);		if (!IsDemo())	break;
	strText = "갤러리4: 예, 저는 SM520을 가지고 있는데요. 무상으로 서비스를 받을 수 있는 기간은 어떻게 되나요?";
	pActor[4]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("07g4a01.wav");
	Wait(dwDU*5);		if (!IsDemo())	break;
	strText = "김딜러: 그건 서비스 센터에 가시면 자세하게 설명 드릴겁니다.";
	pActor[5]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("07dea02.wav");
	Wait(dwDU*4);		if (!IsDemo())	break;
	strText = "김딜러: 그럼 저를 따라 오세요.";
	pActor[5]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("07dea03.wav");
	Wait(dwDU*3);		if (!IsDemo())	break;
	pActor[5]->SetState(AS_STAND | DA_BR);
	Wait(dwDU);		if (!IsDemo())	break;
	m_pStage->ActorMove(pActor[5], TRUE);	// Forward
	Wait(dwDU);		if (!IsDemo())	break;
	m_pStage->ActorMove(pActor[5], TRUE);	// Forward
	Wait(dwDU);		if (!IsDemo())	break;
	m_pStage->ActorMove(pActor[5], TRUE);	// Forward
	Wait(dwDU);		if (!IsDemo())	break;

/////// Scene 8
	LoadStage("0040smin");
	Wait(dwDU*2);		if (!IsDemo())	break;
	pActor[0] = m_pStage->CreateActor(18, CPoint(0,0), TRUE, AS_STAND | DA_FL, TRUE);
	pActor[0] = m_pStage->GetThisActor();
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[0]->SetState(AS_STAND | DA_BR);
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[5] = m_pStage->CreateActor(19, CPoint(255,172), FALSE, AS_STAND | DA_FL);
	pActor[1] = m_pStage->CreateActor(0, CPoint(371,259), FALSE, AS_STAND | DA_BL);
	pActor[2] = m_pStage->CreateActor(5, CPoint(80,268), FALSE, AS_STAND | DA_BR);
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[3] = m_pStage->CreateActor(7, CPoint(255,270), FALSE, AS_STAND | DA_BR);
	pActor[4] = m_pStage->CreateActor(2, CPoint(170,223), FALSE, AS_STAND | DA_FL);
	Wait(dwDU);		if (!IsDemo())	break;
	strText = "김딜러: 저희 서비스센타의 최주임님을 소개해 드리겠습니다.";
	pActor[5]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("08dea01.wav");
	Wait(dwDU*5);		if (!IsDemo())	break;
	pActor[6] = m_pStage->CreateActor(21, CPoint(326,161), FALSE, AS_STAND | DA_FL);
	Wait(dwDU);		if (!IsDemo())	break;
	strText = "최주임: 안녕하십니까? 무엇을 도와 드릴까요?";
	pActor[6]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("08mec01.wav");
	Wait(dwDU*4);		if (!IsDemo())	break;
	strText = "갤러리2: 무상으로 서비스를 받을 수 있는 기간에 대해서 알고 싶은데요.";
	pActor[4]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("08g4a01.wav");
	Wait(dwDU*5);		if (!IsDemo())	break;
	strText = "최주임: 일반 부품은 3년 6만 키로까지이고 엔진 및 동력 전달 부품은 5년 10만 키로까지 무상보증 수리해드립니다.";
	pActor[6]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("08mec02.wav");
	Wait(dwDU*6);		if (!IsDemo())	break;
	strText = "갤러리3: 예, 잘 알겠습니다.";
	pActor[3]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("08g3a01.wav");
	Wait(dwDU*3);		if (!IsDemo())	break;
	strText = "갤러리1: 좀 쉬었다 가지요.";
	pActor[1]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("08g1a01.wav");
	Wait(dwDU*3);		if (!IsDemo())	break;
	strText = "김딜러: 그럼 오토카페로 가실까요?";
	pActor[5]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("08dea02.wav");
	Wait(dwDU*3);		if (!IsDemo())	break;
	strText = "갤러리: 여기도 카페가 있나요?";
	pActor[2]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("08g2a01.wav");
	Wait(dwDU*3);		if (!IsDemo())	break;
	strText = "김딜러: 그럼요. 저를 따라 오세요.";
	pActor[5]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("08dea03.wav");
	Wait(dwDU*3);		if (!IsDemo())	break;
//	pActor[5]->SetState(AS_STAND | DA_BL);
//	Wait(dwDU);		if (!IsDemo())	break;
	m_pStage->ActorMove(pActor[5], FALSE);	// Backward
	Wait(dwDU);		if (!IsDemo())	break;
	m_pStage->ActorMove(pActor[5], FALSE);	// Backward
	Wait(dwDU);		if (!IsDemo())	break;

/////// Scene 9
	LoadStage("0030smin");
	Wait(dwDU*2);		if (!IsDemo())	break;
	pActor[0] = m_pStage->CreateActor(20, CPoint(0,0), TRUE, AS_STAND | DA_FL, TRUE);
	pActor[0] = m_pStage->GetThisActor();
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[0]->SetState(AS_STAND | DA_FL);
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[5] = m_pStage->CreateActor(19, CPoint(243,145), FALSE, AS_STAND | DA_FL);
	pActor[1] = m_pStage->CreateActor(0, CPoint(309,267), FALSE, AS_STAND | DA_FL);
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[2] = m_pStage->CreateActor(5, CPoint(107,307), FALSE, AS_STAND | DA_FL);
	pActor[3] = m_pStage->CreateActor(7, CPoint(36,141), FALSE, AS_STAND | DA_BL);
	Wait(dwDU);		if (!IsDemo())	break;
	pActor[4] = m_pStage->CreateActor(2, CPoint(528,312), FALSE, AS_STAND | DA_BL);
	Wait(dwDU);		if (!IsDemo())	break;
	strText = "김딜러: 여기 계신분들은 대부분 삼성자동차 고객들 입니다.";
	pActor[5]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("09dea01.wav");
	Wait(dwDU*5);		if (!IsDemo())	break;
	strText = "갤러리1: 그럼 여기서 SM5에 대한 많은 정보를 얻을 수 있겠군요?";
	pActor[1]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("09g1a01.wav");
	Wait(dwDU*5);		if (!IsDemo())	break;
	strText = "김딜러: 그렇습니다.";
	pActor[5]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("09g1a02.wav");
	Wait(dwDU*3);		if (!IsDemo())	break;
	strText = "웅성웅성";
	pActor[1]->Chat(strText);
	pActor[2]->Chat(strText);
	pActor[3]->Chat(strText);
	pActor[4]->Chat(strText);
	DisplayText(strText);
	Wait(dwDU);		if (!IsDemo())	break;
	strText = "도우미: 지금까지 보신 것과 같이 M@ll에서는 재미있는 온라인 쇼핑과 판매를 하실 수 있습니다.";
	pActor[0]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("09dou01.wav");
	Wait(dwDU*6);		if (!IsDemo())	break;
	strText = "도우미: 가까운 미래엔 이런 전자상거래를 기반으로 한 커뮤니티 개념의 발전된 차세대 온라인 도시 건설이 실현화 될 것입니다.";
	pActor[0]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("09dou02.wav");
	Wait(dwDU*6);		if (!IsDemo())	break;
	strText = "도우미: 그럼 데모를 봐 주신 여러분께 감사 드리며 이만 데모를 마치겠습니다.";
	pActor[0]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("09dou03.wav");
	Wait(dwDU*6);		if (!IsDemo())	break;
	strText = "도우미: 몰의 세계를 직접 경험하시려면 실행 버튼을 클릭 하십시오.";
	pActor[0]->Chat(strText);
	DisplayText(strText);
	PlayWaveFile("09dou04.wav");
	Wait(dwDU*6);		if (!IsDemo())	break;

	ClearHistory();
	
	OnBtnQuit();
