//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by UDSGen.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_UDSGEN_FORM                 101
#define IDR_MAINFRAME                   128
#define IDR_UDSTYPE                     129
#define IDD_TARGETNAME                  130
#define IDC_LIST1                       1000
#define IDC_TARGET                      1001
#define IDC_PROGRESS1                   1002
#define IDC_GENERATE                    1003
#define IDC_QUIT                        1004
#define IDC_EDIT1                       1005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
