//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by UC2.rc
//
#define IDD_ABOUTBOX                    100
#define CG_IDD_CONTROLPANEL             102
#define CG_ID_VIEW_CONTROLPANEL         103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDS_CLOSE_TEXT                  105
#define IDS_JOIN_CHANNEL_TITLE          106
#define IDS_TIME_REPORT                 107
#define IDS_ABOUT_TEXT                  108
#define IDS_ERROR_TIMER                 109
#define IDS_ERROR_BROWSER               110
#define IDS_UNICHAT_HOMEURL             111
#define CG_IDD_HISTORYPANEL             112
#define IDS_HISTORY_PANEL               113
#define CG_ID_VIEW_HISTORYPANEL         114
#define IDS_PROPSHT_CAPTION             115
#define IDD_PP_CREATE_CHANNEL           116
#define IDS_DATA_TRANSMISSION_DONE      116
#define IDD_PP_CHANNEL                  117
#define IDS_TRANSFER_MEMBER_CHANNEL     117
#define IDD_PP_ACTOR                    118
#define IDS_TRANSFER_MEMBER_ALL_CHANNEL 118
#define IDD_PP_MEMBER1                  119
#define IDD_PP_MEMBER2                  120
#define DIB_ROOMKEY                     122
#define ID_INDICATOR_DATE               123
#define ID_INDICATOR_TIME               124
#define IDR_MAINFRAME                   128
#define IDR_UC2TYPE                     129
#define IDS_QUERY_LINE_BUSY             129
#define IDD_DIALOG_LOGIN                130
#define IDS_INVITE_SELECT_MEMBER        130
#define IDD_CLOSE                       131
#define IDS_INVITE_OPEN_CHANNEL         131
#define IDR_MENU_ACTOR                  132
#define IDS_INVITE_ERROR_MYSELF         132
#define IDB_IL_CHANNEL                  133
#define IDC_ARROW_LT                    134
#define IDS_INVITE_OK                   134
#define IDC_ARROW_LB                    135
#define IDS_INVITE_FAIL                 135
#define IDC_ARROW_RT                    136
#define IDS_JOINED_CHANNEL              136
#define IDC_ARROW_RB                    137
#define IDS_KICKOFF_REASON              137
#define IDC_HGREP_DOWN                  138
#define IDS_MEMBER_ENTRY                138
#define IDC_HGREP_UP                    139
#define IDS_MEMBER_EXIT                 139
#define IDD_DLG_MEMBER                  140
#define IDS_INVITATION                  140
#define IDS_PRIVATE_MESSAGE             141
#define IDD_INPUT_INT                   141
#define IDS_SELECT_CHANNEL              142
#define IDS_FILL_CHANNEL_TITLE          143
#define IDS_NO_CHANNEL_OPENED           144
#define IDS_CLICK_CHANNEL_TITLE         145
#define IDS_RECEIVING_CHANNELS_LIST     146
#define IDS_INVALID_CHANNEL_NAME        147
#define IDS_LEAVE_THIS_CHANNEL          148
#define IDB_IL_MEMBER                   149
#define IDS_CANNOT_JOIN_CHANNEL         149
#define IDS_INVALID_CHATID              150
#define IDS_CONNECTION_TYPE_GLOBAL      151
#define IDS_CONNECTION_TYPE_LOCAL       152
#define IDR_MENU_ACTOR_OTHER            167
#define IDD_INPUT_PASSWORD              169
#define IDD_DIALOG_WHISPER              172
#define IDD_PROGRESS_DIALOG             173
#define IDC_EDIT_MSG                    1000
#define IDC_DISPLAY                     1001
#define IDC_BTN_CREATE                  1002
#define IDC_PROGRESS                    1002
#define IDC_BTN_ROOM                    1003
#define IDC_BTN_MEMBER                  1004
#define IDC_BTN_SOUND                   1005
#define IDC_BTN_HISTORY                 1006
#define IDC_BTN_QUIT                    1007
#define IDC_EDIT_NAME                   1008
#define IDS_QUERY_NO_MATCH              1008
#define IDC_RADIO_LAN                   1009
#define IDC_EDIT_CHAT_ID                1009
#define IDS_CONNECT_LAN                 1009
#define IDC_RADIO_MODEM                 1010
#define IDC_EDIT_UNITEL_ID              1010
#define IDS_CONNECT_MODEM               1010
#define IDC_EDIT_HOMEPAGE               1011
#define IDS_WELCOME_TO_LOBBY            1011
#define IDC_EDIT_NICKNAME               1012
#define IDC_EDIT_PASSWORD               1013
#define IDC_PROGRESSBAR                 1013
#define IDC_CB_HOST                     1014
#define IDC_EDIT_PROFILE                1014
#define IDS_CANCELED_CONNECTION         1014
#define IDS_LOGIN_BEGIN                 1015
#define IDC_LIST_CHANNEL                1015
#define IDC_EDIT_AGE                    1015
#define IDS_LOGIN_CONNECTING            1016
#define IDC_SPIN_AGE                    1016
#define IDC_EDIT_SEND                   1017
#define IDC_ST_MESSAGE                  1018
#define IDC_ST_TIME_REPORT              1019
#define IDC_LB_ACTORS                   1019
#define IDS_CONNECTING_SERVER           1019
#define IDC_EDIT_HISTORY                1020
#define IDC_SB_ACTOR                    1020
#define IDS_LOGGING_ON_SERVER           1021
#define IDC_ST_SECONDS                  1021
#define IDS_TRYING_BACKUP_ID            1022
#define IDC_ST_VERSION                  1022
#define IDC_STATIC_NICK                 1023
#define IDS_CONNECTION_FAILED           1023
#define IDC_BTN_MUD                     1023
#define IDS_ERROR_TIMEOUT               1024
#define IDC_ST_STAGEID                  1024
#define IDS_ERROR_NOT_WIN95             1025
#define IDC_LIST_MEMBER                 1026
#define IDS_ERROR_WRITE_REGISTRY        1026
#define IDC_EDIT_INT                    1026
#define IDC_STATIC_MESSAGE              1027
#define IDS_ENTER_PASSWORD              1027
#define IDC_BTN_DEFAULT                 1027
#define IDC_BTN_RENEW                   1028
#define IDS_DEMO_1                      1028
#define IDC_STATIC_CHANNEL_COUNT        1029
#define IDS_DEMO_2                      1029
#define IDC_STATIC_MEMBER_COUNT         1030
#define IDS_DEMO_3                      1030
#define IDC_COMBO_SEX                   1031
#define IDC_BTN_INVITE                  1031
#define IDS_DEMO_4                      1031
#define IDS_DEMO_5                      1032
#define IDS_DEMO_6                      1033
#define IDC_STATIC_REALNAME             1034
#define IDS_DEMO_7                      1034
#define IDS_DEMO_8                      1035
#define IDS_DEMO_9                      1036
#define IDS_DEMO_10                     1037
#define IDS_DEMO_11                     1038
#define IDS_DEMO_12                     1039
#define IDS_DEMO_13                     1040
#define IDC_EDIT_CHANNEL_NAME           1041
#define IDS_DEMO_14                     1041
#define IDS_ACTOR_PROPSHT_CAPTION       1042
#define IDC_RADIO_PUBLIC                1043
#define IDS_SELECT_STAGE                1043
#define IDC_RADIO_PRIVATE               1044
#define IDS_MUD_MODE                    1045
#define IDS_EPILOGUE00                  1046
#define IDS_EPILOGUE01                  1047
#define IDS_EPILOGUE02                  1048
#define IDC_LB_BACKGROUND               1049
#define IDS_EPILOGUE03                  1049
#define IDS_EPILOGUE04                  1050
#define IDC_STATIC_VERSION              1051
#define IDS_PROGRESS_INIT_BIND          1051
#define IDC_STATIC_UNITEL_ID            1052
#define IDS_PROGRESS_PREPARE            1052
#define IDC_STATIC_SEXAGE               1053
#define IDS_PROGRESS_DOWNLOAD_FAIL      1053
#define IDS_PROGRESS_DOWNLOADED         1054
#define IDC_EDIT_TEXT                   1055
#define IDS_PROGRESS_ALL_FILES_DONE     1055
#define IDC_STATIC_TO                   1056
#define IDS_CLOSE_ON_NEW_RIT            1056
#define IDS_CHANNEL_OUT                 1057
#define IDS_RIT_NO_BEHAVIORS            1058
#define IDS_RIT_NO_SPRITES              1059
#define IDS_RIT_NO_WAVES                1060
#define IDS_RIT_NO_MIDIS                1061
#define IDS_RIT_NO_STAGES               1062
#define IDS_RIT_NO_SERVERIPS            1063
#define IDS_ENTER_BUBBLE_TEXT_LIMIT     1064
#define IDS_ENTER_BUBBLE_TIME           1065
#define IDS_BTN_MUD                     1066
#define IDS_BTN_USER                    1067
#define IDS_HELP_SIMPLE                 1068
#define ID_VIEW_ADJUST_WINDOW           32771
#define ID_VIEW_PAUSE                   32772
#define ID_ACTOR_VOICE                  32773
#define ID_ACTOR_MOVE_F                 32774
#define ID_ACTOR_MOVE_B                 32775
#define ID_ACTOR_TURN_L                 32776
#define ID_ACTOR_TURN_R                 32777
#define ID_ACTOR_STATE_0                32778
#define ID_ACTOR_STATE_1                32779
#define ID_ACTOR_STATE_2                32780
#define ID_ACTOR_PROP                   32781
#define IDS_TURNING_OFF_DEMO            32782
#define ID_EDIT_NOTEPAD                 32784
#define ID_HELP_HOMEPAGE                32785
#define ID_VIEW_DEMO                    32786
#define ID_ACTOR_HYPERLINK              32787
#define ID_CONNECT_SYNC                 32788
#define ID_VIEW_TEXT_LIMIT              32789
#define ID_VIEW_BUBBLE_TIME             32790
#define ID_VIEW_BUBBLE_TEXTLIMIT        32791
#define ID_ACTOR_ACTION_0               32805
#define ID_ACTOR_ACTION_1               32806
#define ID_ACTOR_ACTION_2               32807
#define ID_ACTOR_ACTION_3               32808
#define ID_ACTOR_ACTION_4               32809
#define ID_ACTOR_ACTION_5               32810
#define ID_ACTOR_ACTION_6               32811
#define ID_ACTOR_ACTION_7               32812
#define ID_ACTOR_ACTION_8               32813
#define ID_ACTOR_ACTION_9               32814
#define ID_MAKEHOST                     32823
#define ID_WHISPER                      32830
#define ID_IGNORE                       32831
#define ID_KICKOUT                      32832

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1028
#define _APS_NEXT_SYMED_VALUE           125
#endif
#endif
