#if !defined(STDAFX_H__012F24C9_35B0_11D0_BF2D_0000E8D0D146__INCLUDED_)
#define STDAFX_H__012F24C9_35B0_11D0_BF2D_0000E8D0D146__INCLUDED_

// stdafx.h : include file for standard system include files,
//      or project specific include files that are used frequently,
//      but are changed infrequently
#define STRICT


#include <atlbase.h>
//You may derive a class from CComModule and use it if you want to override
//something, but do not change the name of _Module
extern CComModule _Module;
#include <atlcom.h>
#include <atlctl.h>

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(STDAFX_H__012F24C9_35B0_11D0_BF2D_0000E8D0D146__INCLUDED)
