//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BMC.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_BMCTYPE                     129
#define IDD_PALETTE                     130
#define IDD_INPUT_DLG                   131
#define IDC_SB_PAL_RED                  1000
#define IDC_SB_PAL_GREEN                1001
#define IDC_SB_PAL_BLUE                 1002
#define IDC_ST_PAL_RGB                  1003
#define IDC_CHECK_SHOW_INDEX            1004
#define IDC_EDIT_STRING                 1005
#define ID_FILE_LOADBKGND               32771
#define ID_FILE_LOADSPRITE              32776
#define ID_VIEW_PALETTE                 32777
#define ID_VIEW_OUTLINE                 32778
#define ID_FILE_SAVE_BKG                32779
#define ID_FILE_SAVE_SPRITE             32780
#define ID_VIEW_640x480                 32781
#define ID_VIEW_800x600                 32782

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
