//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MapEd.rc
//
#define IDD_ABOUTBOX                    100
#define DIB_GRID_64X32                  101
#define ID_SPRITE_TYPE                  104
#define ID_ACTOR_ELEVATION              105
#define IDB_SPLASH                      106
#define DIB_ROOMKEY                     107
#define IDR_MAINFRAME                   128
#define IDR_MAPEDTYPE                   129
#define IDS_ENTER_MSPT                  129
#define IDD_DIALOG_VIEW                 130
#define IDS_ENTER_ELEVATION             131
#define IDS_ENTER_ACTOR_ELEVATION       132
#define IDS_ENTER_TILE_ELEVS            133
#define IDR_MENU_TILE                   134
#define IDS_ENTER_STAGE_TITLE           135
#define IDS_ENTER_STAGE_MUSIC           136
#define IDS_ENTER_STAGE_LINK            137
#define IDB_IL_OBJECT                   138
#define IDD_ENVIRONMENT                 139
#define IDC_PIXEL                       140
#define IDD_CLOSE                       141
#define IDD_GETINT                      142
#define IDD_GETSTRING                   143
#define IDD_PALETTE                     144
#define IDR_MENU_GRID                   145
#define IDC_GREP_UP                     159
#define IDC_GREP_DOWN                   160
#define IDC_LIST_OBJ                    1000
#define IDC_SB_PAL_RED                  1000
#define IDC_ST_CELL_INFO                1001
#define IDC_SB_PAL_GREEN                1001
#define IDC_SB_CELL_ID                  1002
#define IDC_SB_PAL_BLUE                 1002
#define IDC_ST_PAL_RGB                  1003
#define IDC_EDIT_SCREEN_W               1003
#define IDC_CHECK_SHOW_INDEX            1004
#define IDC_EDIT_SCREEN_H               1004
#define IDC_EDIT_TILE_W                 1005
#define IDC_EDIT_TILE_H                 1006
#define IDC_EDIT_DATA_PATH              1007
#define IDC_EDIT_PALFILE                1008
#define IDC_SPIN1                       1011
#define IDC_ST_CURRENT_INT              1013
#define IDC_EDIT_NEW_INT                1014
#define IDC_EDIT_STRING                 1015
#define IDS_RIT_NO_BEHAVIORS            1058
#define IDS_RIT_NO_SPRITES              1059
#define IDS_RIT_NO_WAVES                1060
#define IDS_RIT_NO_MIDIS                1061
#define IDS_RIT_NO_STAGES               1062
#define IDS_RIT_NO_SERVERIPS            1063
#define ID_FILE_LOADBKGND               32771
#define ID_FILE_LOADSPRITE              32772
#define ID_VIEW_GRID                    32776
#define ID_FILE_LOAD_RIT                32777
#define ID_FILE_LOAD_STAGE              32779
#define ID_VIEW_EARTH                   32783
#define ID_FILE_LOAD_MAP                32784
#define ID_FILE_SAVE_STAGE              32785
#define ID_FILE_SAVE_MAP                32786
#define ID_VIEW_PALETTE                 32787
#define ID_OPTIONS_ENV                  32792
#define ID_EDIT_MODE                    32794
#define ID_SPRITE_ELEVATION             32796
#define ID_SPRITE_FLIP                  32797
#define ID_SPRITE_VERTICAL              32798
#define ID_SPRITE_OPACITY100            32799
#define ID_SPRITE_OPACITY50             32800
#define ID_SPRITE_OPACITY25             32801
#define ID_SPRITE_OPACITY12             32802
#define ID_SPRITE_DELETE                32803
#define ID_SPRITE_FLIPVERT              32804
#define ID_VIEW_MAP_ONLY                32805
#define ID_VIEW_GRAPH                   32808
#define ID_EDIT_TILE_COORD              32810
#define ID_VIEW_PAUSE                   32812
#define ID_MENU_ANIMATION               32814
#define ID_MENU_ANI_REPEAT              32815
#define ID_MENU_ANI_FADE                32816
#define ID_MENU_NOANI                   32817
#define ID_SPRITE_OPACITY75             32818
#define ID_MENU_ANI_RANDOM              32819
#define ID_MENU_STAGE_TITLE             32820
#define ID_EDIT_STAND                   32822
#define ID_MENU_DA_FR                   32825
#define ID_MENU_DA_FL                   32826
#define ID_MENU_DA_BL                   32827
#define ID_MENU_DA_BR                   32829
#define ID_EDIT_CREATE_MODE             32830
#define ID_MENU_RECALC_DA               32832
#define ID_MENU_DA_OPEN                 32833
#define ID_MENU_DA_CLOSED               32834
#define ID_MENU_SYNC_EA                 32835
#define ID_VIEW_NOELEV                  32836
#define ID_MENU_STAGE_MUSIC             32837
#define ID_VIEW_EA_GRAPH                32838
#define ID_MENU_ELEVATION               32840
#define ID_MENU_EXIT_POINT              32841
#define ID_MENU_ENTRY_POINT             32842

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32843
#define _APS_NEXT_CONTROL_VALUE         1016
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
